---
- name: Installeer Python MySQL module
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Installeer MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  notify: restart mysql

- name: Zorg dat MySQL service draait
  service:
    name: mysql
    state: started
    enabled: yes

- name: Configureer MySQL om externe verbindingen toe te staan
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: restart mysql

- name: Maak MySQL gebruiker aan
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: '%'
    priv: '*.*:ALL'
    state: present
