#SPDX-License-Identifier: MIT-0
---
# handlers file for galaxyAnsible

# handler voor apache
- name: restart apache
  service:
    name: apache2
    state: restarted

# handler voor php
- name: restart php
  service:
    name: php7.4-fpm
    state: restarted


# handler voor mysql
- name: restart mysql
  service:
    name: mysql
    state: restarted

